import { wrapper } from '@store/reducer';
import type { GetServerSideProps } from 'next'
import Head from 'next/head'

export default function Page() {
  return (
    <>
      <Head>
        <title>Create Next App 13</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        test
      </main>
    </>
  )
}
